### PR TITLE
Strips username@ and only removes trailing .git from remote if it exists.

### PR DESCRIPTION
**Pull request by s2tephen**
Edits as discussed in #2. Sometimes the remote URL doesn't actually contain ".git" so this approach uses regex to only remove the substring if it exists.

### CODE REVIEW

**Comment by henrikdahl** [comment]
Fair point! Was focusing on speed and assumed it's always present. ✌️

**Comment by henrikdahl** [comment]
@s2tephen Weird, `.replace(/.git$/, '')` doesn't actually remove `.git` for me. Works with `.replace(/\.git/, '')` for me.

**Comment by s2tephen** [comment]
Oh, looks like I forgot to escape the period in `.git`, but that shouldn't make a difference — I'm not sure why the end of line selector isn't working for you.

Not including `$` could potentially be a problem if the remote URL contains `www.git`, e.g. `https://www.github.com/user/repo`. GitHub doesn't include `www.` by default but if the remote is added manually, it's accepted. This also doesn't consider other git repository platforms/private repos, which could include `.git` anywhere in the URL. The `$` is essential for isolating file extensions only.

**Comment by henrikdahl** [comment]
I'm not either. Works fine in [Scriptular](http://scriptular.com/#%5C.git%24%7C%7C%7C%7C%7C%7C%7C%7C%5B%22https%3A%2F%2Fhenrikdahl%40github.com%2Fhenrikdahl%2Fhyper-statusline.git%22%5D)

However, doesn't work in Hyper for me.

replace

**Comment by s2tephen** [comment]
See if #8 fixes the problem.

**Pull request merged**
