### PR TITLE
Fixes issue getting win32 current working directory

### PR DESCRIPTION
**Pull request by dougd**
Resubmitted PR due to issues with previous one and tabs. Refactored to try to get windows current working directory using regex as lsof not available in win32. Not 100% accurate, but better than no
support at all. Needs tested on mac and linux.

### CODE REVIEW

**Comment by Stanzilla** [comment]
Nice!

**Comment by haustraliaer** [comment]
This is working great for me on windows 10 v1607 - thanks @dougd!

**Comment by henrikdahl** [comment]
This is neat! I'm gonna try this out later today. Thanks for your contribution and sorry for the massive delay ✌️

**Comment by Stanzilla** [comment]
I noticed this only starts working after you sent your first command to the terminal, before that the statusbar stays blank

**Comment by haustraliaer** [comment]
Ah true - I see this as well @Stanzilla - didn't notice because I'd usually cd into somewhere first.

Now I'm using hypercwd (windows PR) I see it on a new tab though.

**Comment by Stanzilla** [comment]
You're talking about this one here, right? https://github.com/hharnisc/hypercwd/pull/21 Looks like a similar approach than the one by @dougd

**Comment by haustraliaer** [comment]
Yep - that's what I'm using as a local plugin.

**Comment by Stanzilla** [comment]
@dougd are you on win10 btw?

**Comment by dougd** [comment]
On Win7. Does it not work on Win10?
  
  
  
  
Cheers,
 Doug       
  

  
  
>

**Comment by Stanzilla** [comment]
No I just thought about the fact that Win10 has the Linux Subsystem and you could use that instead of a regex. I just started playing around with it and


```js
const setCwd = (pid) => {
    exec(`bash.exe -c lsof -p ${pid} | awk '$4=="cwd"' | tr -s ' ' | cut -d ' ' -f9-`, (err, stdout) => {
        cwd = stdout.trim();
        setGit(cwd);
    });
};
```
resulted in https://i.imgur.com/h2L6aE0.png 😄

**Comment by dougd** [comment]
Ah I see 👍 would we want different code path for win7 and win10? I suppose we already have windows, mac and linux :-)   
  
  
  
  
Cheers,
 Doug       
  

  
  
>

**Comment by Stanzilla** [comment]
Depends on performance and if I get it working, I guess. If your solution is faster than going to bash on Windows then it's not worth it to make a special path.

**Comment by dougd** [comment]
Your solution if it flies would yield more reliable results....
  
  
  
  
Cheers,
 Doug       
  

  
  
>

**Comment by dougd** [comment]
Looks like the plugin as moved on since I did this work, closing and there is another pending PR to address this.

**Pull request closed without merging**
