### PR TITLE
Added support for Windows

### PR DESCRIPTION
**Pull request by pevecyan**
Small fix to support Windows

### CODE REVIEW

**Comment by pevecyan** [comment]
I checked older windows PR and there are conflicts so I reopened this one.

**Comment by dougd** [comment]
Tried it and works great for me! Cheers! Could this get merged in?

**Comment by henrikdahl** [comment]
Thanks @pevecyan @dougd ✌️

**Comment by dougd** [comment]
Magic thanks! 👍

**Pull request merged**
